WPI_SAE_Website/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^sponsors/', include('sponsors.urls', namespace="sponsors")),
    url(r'^gallery/', include('images.urls', namespace="images")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^', include('sae_globals.urls', namespace="sae_globals")),
]

if settings.DEBUG is True:
    urlpatterns.insert(-1, *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

images/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w.@+-]+)-(?P<pk>\d+)/$', views.image, name='image'),
]

news/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w.@+-]+)-(?P<pk>\d+)/$', views.post, name='post'),
]

images/models.py
import hashlib
import os

from PIL import Image
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify

from sae_globals.models import SAEBaseModel, b_n


def validate_image_ext(value):
    """Make sure that uploaded image files only have extensions found in the list below."""
    image_file_exts = ['.jpg', '.jpeg', '.png', ]
    ext = os.path.splitext(value.name)[1].lower()
    if image_file_exts and ext not in image_file_exts:
        if len(image_file_exts) >= 3:
            allowed_str = ', '.join(image_file_exts[:-1]) + ', and ' + image_file_exts[-1]
        else:
            allowed_str = ' and '.join(image_file_exts)
        raise ValidationError("This file is not the right type. Only {} files are allowed.".format(allowed_str))


class ImageModel(SAEBaseModel):
    def upload_to(self, current_filename) -> str:
        """Function called to dynamically upload a file to a specific location on the file system."""
        return os.path.join('images', current_filename)

    title = models.CharField('Title', max_length=500)

    file = models.ImageField('File', validators=[validate_image_ext, ], upload_to=upload_to, **b_n)
    file_hash = models.CharField('File Hash', max_length=500, **b_n)

    tn = models.ImageField('Thumbnail', **b_n)

    ROLE_HOME_PAGE = 'HP'
    ROLE_NEWS = 'NW'
    ROLE_PROJECTS = 'PR'
    ROLE_IMAGES = 'GA'
    ROLE_SPONSORS = 'SP'
    ROLE_CONTACT = 'CT'
    ROLE_CHOICES = (
        (ROLE_HOME_PAGE, 'Home Page'),
        (ROLE_NEWS, 'News Page'),
        (ROLE_PROJECTS, 'Projects Page'),
        (ROLE_IMAGES, 'Gallery Page'),
        (ROLE_SPONSORS, 'Sponsors Page'),
        (ROLE_CONTACT, 'Contact Page'),
    )
    role = models.CharField('Image Role', max_length=2, choices=ROLE_CHOICES, **b_n)

    slugified_field = 'title'

    def save(self, *args, **kwargs):
        # Save this model directly so that the file gets uploaded.
        self.slug = slugify(self.title)
        super(ImageModel, self).save(*args, **kwargs)

        # Create thumbnail if file has changed
        if self.file:
            new_file_hash = self._create_file_hash(self.file.file)
            if self.file_hash != new_file_hash:
                self._make_tn()
                self.file_hash = new_file_hash

        # If another image shares the same role as this image, remove theirs.
        if self.role:
            same_role_images = ImageModel.objects.filter(role=self.role).exclude(pk=self.pk)
            for i in same_role_images:
                i.role = None
                i.save()

        models.Model.save(self)

    def _make_tn(self):
        TN_SIZE = (600, 0xFFFFFFFF)
        """Create and save the thumbnail for the photo (simple resize with PIL)."""
        # Open the currently loaded file and then scale it.
        try:
            #                       LOLOLOLOL
            image = Image.open(self.file.file.file)
        except FileNotFoundError:
            # Good chance we are moving files around.
            return
        except ValueError:
            # fs doesn't have a file associated with it.
            return

        ftype = image.format
        try:
            image.thumbnail(TN_SIZE, Image.ANTIALIAS)
        except OSError:
            # TODO: Either log error or use gimp cli to fix image.
            error = True
        else:
            error = False

        # Get filename and add file_id to it.
        temp = self.file.file.name.lstrip(settings.MEDIA_ROOT).split('.')
        temp.insert(-1, 'tn')
        tn_filename = ".".join(temp)

        # Save the tn to a real file via a ContentFile
        abs_tn_filepath = os.path.join(settings.MEDIA_ROOT, tn_filename)
        os.makedirs(os.path.dirname(abs_tn_filepath), exist_ok=True)
        with open(abs_tn_filepath, 'wb') as tn_out:
            if not error:
                image.save(tn_out, ftype)

        self.tn = tn_filename

    @staticmethod
    def _create_file_hash(file, buffer_size=65536):
        """Hash self.file and return the sha1 sum"""
        sha1 = hashlib.sha1()
        data = file.read(buffer_size)
        while data:
            sha1.update(data)
            data = file.read(buffer_size)
        return sha1.hexdigest()

    @property
    def tn_url(self):
        return self.tn.url if self.tn else self.file_url

    @property
    def file_url(self):
        return self.file.url if self.file else ''

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Image"

images/views.py
from collections import defaultdict

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from news.views import filter_by_month_year

from .models import ImageModel


def index(request):
    images = ImageModel.get_enabled(request).filter(Q(role='') | Q(role=None)).order_by('-pub_date')

    dates = defaultdict(int)
    time_str = "%s %d"
    for p in images:
        dates[time_str % (p.pub_date.strftime('%B'), p.pub_date.year,)] += 1

    images, filtered_month = filter_by_month_year(request, images)
    if filtered_month:
        subtitle = filtered_month.capitalize()
    else:
        subtitle = None

    paginator = Paginator(images, 25)  # Show 25 posts per page
    try:
        images = paginator.page(request.GET.get('page', 1))
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        images = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        images = paginator.page(paginator.num_pages)

    return render(request, 'images/index.html', {'images': images, 'dates': dict(dates), 'subtitle': subtitle, })


def image(request, slug, pk):
    image_obj = get_object_or_404(ImageModel.get_enabled(request), pk=pk)
    return render(request, 'images/image.html', {'image': image_obj, })

images/templates/images/image.html
{% extends 'sae_globals/base.html' %}

{% block meta_title %}{{ image.title }} | Gallery{% endblock %}

{% block content %}
    <div class="container main-content">
        <div class="card post">
            <img class="card-img-top img-fluid" src="{{ image.file_url }}" alt="{{ image.title }}">
            <div class="card-block">
                <h4 class="card-title">{{ image.title|safe }}</h4>
            </div>
            <div class="card-block">
                <p class="card-text text-right">
                    <small class="text-muted">Published {{ image.pub_date|date }}</small>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

images/templates/images/index.html
{% extends 'sae_globals/base.html' %}

{% block meta_title %}Gallery{% endblock %}

{% block content %}
    {% include 'sae_globals/title_background.html' with title='Gallery' image_role='GA' %}
    <div class="container main-content sidebar-container">
        <div class="row">
            <div class="col-sm-9 content-column">
                <div class="container my-4">
                    <div class="card-columns">
                        {% for image in images %}
                            <div class="card">
                                <a class="card-img-top" href="{{ image.file_url }}" data-toggle="lightbox"
                                   data-gallery="gallery" data-type="image">
                                    <img class="img-fluid full-width" src="{{ image.tn_url }}" alt="Card image cap">
                                </a>
                                <div class="card-block">
                                    <h4 class="card-title"><a
                                            href="{% url 'images:image' image.slug image.pk %}">{{ image.title|safe }}</a>
                                    </h4>
                                    {% comment %}<h6 class="card-subtitle text-muted">By {{ image.created_by }}</h6>{% endcomment %}
                                    <p class="card-text text-right">
                                        <small class="text-muted">Published {{ image.pub_date|date }}</small>
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <nav class="full-width my-4" aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if images.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ images.previous_page_number }}{% if subtitle %}&date={{ subtitle|slugify }}{% endif %}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for i in images.paginator.page_range %}
                                <li class="page-item {% if i == images.number %}active{% endif %}">
                                    <a class="page-link" href="?page={{ i }}{% if subtitle %}&date={{ subtitle|slugify }}{% endif %}">{{ i }}</a>
                                </li>
                            {% endfor %}
                            {% if images.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ images.next_page_number }}{% if subtitle %}&date={{ subtitle|slugify }}{% endif %}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="col-sm-3 sidebar-column" id="sidebar">
                <h4 class="sidebar-content-title" data-toggle="sidebar">Filter by Month</h4>
                <div class="sidebar-content">
                    <ul class="date-list">
                        {% for date, count in dates.items %}
                            <li><a href="?date={{ date|slugify }}">{{ date }} ({{ count }})</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div><!-- .row -->
    </div><!-- .container -->
{% endblock %}