WPI_SAE_Website/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^sponsors/', include('sponsors.urls', namespace="sponsors")),
    url(r'^gallery/', include('images.urls', namespace="images")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^', include('sae_globals.urls', namespace="sae_globals")),
]

if settings.DEBUG is True:
    urlpatterns.insert(-1, *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

news/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w.@+-]+)-(?P<pk>\d+)/$', views.post, name='post'),
]

sae_globals/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
]

sae_globals/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.core.handlers.wsgi import WSGIRequest
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.utils.text import slugify

from crequest.middleware import CrequestMiddleware as Crequest


b_n = {
    'blank': True,
    'null': True,
}


class SearchQueryset(models.QuerySet):
    def search(self, query):
        # https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/search/
        # Build search vector
        search_q = SearchQuery(query)
        vector = None
        for field in self.model.search_fields:
            if type(field) == tuple:
                field_name = field[0]
                if len(field) < 2:
                    field_weight = 'B'
                else:
                    field_weight = field[1]
            else:
                field_name = field
                field_weight = 'B'
            if not vector:
                vector = SearchVector(field_name, weight=field_weight)
            else:
                vector += SearchVector(field_name, weight=field_weight)
        return self.annotate(rank=SearchRank(vector, search_q)).filter(rank__gte=0.1).order_by('-rank')


class SAEManager(models.Manager):
    def get_queryset(self):
        return SearchQueryset(model=self.model, using=self._db, hints=self._hints)

    def search(self, query) -> models.QuerySet:
        return self.get_queryset().search(query)

    def get_enabled(self, request: WSGIRequest=None) -> models.QuerySet:
        # Always want public models
        enabled_filter = models.Q(enabled=SAEBaseModel.PUBLIC)
        if not request:
            request = Crequest.get_request()
        if request and request.user.is_staff:
            # If staff, get the staff ones too.
            enabled_filter |= models.Q(enabled=SAEBaseModel.STAFF_ONLY)
        return self.get_queryset().filter(enabled_filter)


class SAEBaseModel(models.Model):
    PUBLIC = 'PB'
    STAFF_ONLY = 'SO'
    NONE = 'NO'
    ENABLED_CHOICES = (
        (PUBLIC, 'Public'),
        (STAFF_ONLY, 'Staff Only'),
        (NONE, 'None'),
    )

    # Should this model be displayed?
    enabled = models.CharField('Enabled', max_length=2, default=PUBLIC, choices=ENABLED_CHOICES)
    # When was this model originally published? Can be modified, useful for putting dates further in the past.
    pub_date = models.DateTimeField('Date Published', default=timezone.now)
    # When was this model last updated? Automatically set.
    last_update = models.DateTimeField('Lasted Updated', auto_now=True, auto_now_add=False)
    # User to create
    created_by = models.ForeignKey(User, related_name='%(app_label)s_%(class)s_created', **b_n)
    # Last user to make a change
    last_edited_by = models.ForeignKey(User, related_name='%(app_label)s_%(class)s_last_edited', **b_n)

    slug = models.CharField('Slug', max_length=500, **b_n)

    objects = SAEManager()

    slugified_field = None

    def save(self, *args, **kwargs):
        request = Crequest.get_request()
        if not self.pk:
            self.created_by = request.user
        self.last_edited_by = request.user
        if self.slugified_field:
            self.slug = slugify(getattr(self, self.slugified_field))
        super(SAEBaseModel, self).save(*args, **kwargs)

    def was_published_recently(self) -> bool:
        """
        Checks if current model was published within the past 180 days. Models published in the future return false.

        :rtype: bool
        """
        now = timezone.now()
        return now - timedelta(days=180) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Recent?'

    def is_new(self) -> bool:
        """
        Proxy for checking if a model is new. Allows for easy swapping of published vs updated for determining if
        something should be marked as new.

        :rtype: bool
        """
        return self.was_published_recently()

    def was_updated_recently(self) -> bool:
        """
        Same as `was_published_recently()` except it checks last_update instead of pub_date.

        :return: bol
        """
        now = timezone.now()
        return now - timedelta(days=180) <= self.last_update <= now

    @classmethod
    def get_enabled(cls, request=None):
        return cls.objects.get_enabled(request)

    was_updated_recently.admin_order_field = 'last_update'
    was_updated_recently.boolean = True
    was_updated_recently.short_description = 'Recent?'

    class Meta:
        abstract = True


class AbstractPostModel(SAEBaseModel):
    title = models.CharField('Title', max_length=500)
    content = models.TextField('Content')
    image = models.ForeignKey('images.ImageModel', **b_n)
    slugified_field = 'title'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(AbstractPostModel, self).save(*args, **kwargs)

    @property
    def image_tn_url(self):
        return self.image.tn_url if self.image else ''

    @property
    def image_file_url(self):
        return self.image.file_url if self.image else ''

    @property
    def image_title(self):
        return self.image.title if self.image else self.title

    def abs_url(self):
        return ''

    def __str__(self):
        return self.title

    class Meta:
        abstract = True

sae_globals/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Name:"
        self.fields['contact_email'].label = "Email:"
        self.fields['content'].label = "Message:"

sae_globals/views.py
from django.core.mail import EmailMessage
from django.shortcuts import render, reverse
from django.template import Context
from django.template.loader import get_template
from django.conf import settings
from django.http import HttpResponseRedirect

from sponsors.models import SponsorModel

from .forms import ContactForm


def home(request):
    return render(request, 'sae_globals/home.html', {'top_sponsors': SponsorModel.top_sponsors(), })


def contact(request):
    if request.method == 'POST':
        form = ContactForm(data=request.POST)

        if form.is_valid():
            contact_name = form.cleaned_data.get('contact_name', '')

            contact_email = form.cleaned_data.get('contact_email', '')
            form_content = form.cleaned_data.get('content', '')

            # Email the profile with the contact information
            template = get_template('sae_globals/contact_email.html')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Your website" + '',
                [settings.DEFAULT_FROM_EMAIL, ],
                headers={'Reply-To': contact_email, }
            )
            email.send()
            return HttpResponseRedirect(reverse('sae_globals:contact') + "?success=True")
    else:
        form = ContactForm()

    return render(request, 'sae_globals/contact.html', {'form': form, })

sae_globals/templates/sae_globals/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8860-1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# Theme colors #}
    <meta name="theme-color" content="#19ABFF">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#19ABFF">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="#19ABFF">

    <title>{% block meta_title %}Home{% endblock %} | WPI SAE</title>

    <meta name="description"
          content="{% block meta_description %}{# TODO: DESCRIPTION #}{% endblock %}"/>

    <meta name="google-site-verification" content="IPh7Uy8RN4kkTyUvodxoEzX9kbl-EyMOl5bui8BHCFw"/>
    <meta name="keywords" content="{# TODO: KEYWORDS #}
                                    {% block meta_keywords %}{% endblock %}"/>

    <link rel="shortcut icon" href="{# TODO: ICON #}" type="image/x-icon"/>

    {# JQUERY #}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    {% comment %}
    {# BOOTSTRAP 3 #}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    {% endcomment %}

    {# BOOTSTRAP 4 #}
    <link rel="stylesheet" href="{% static 'sae_globals/js/tether-1.3.3/dist/css/tether.min.css' %}">
    <script src="{% static 'sae_globals/js/tether-1.3.3/dist/js/tether.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'sae_globals/bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'sae_globals/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    {# BOOTSTRAP EKKO LIGHTBOX #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.1.1/ekko-lightbox.min.css"
          crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.1.1/ekko-lightbox.min.js"
            crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $(document).on('click', '[data-toggle="lightbox"]', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });
            $('[data-toggle="sidebar"]').click(function () {
                $('#sidebar').toggleClass('active')
            });
        });
    </script>

    <link rel="stylesheet" href="{% static 'sae_globals/css/main.css' %}">

    {% block extra_head %}
    {% endblock %}


</head>

<body>
<div id="main">

    {% include 'sae_globals/header.html' %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'sae_globals/footer.html' %}
</div>

</body>

</html>

sae_globals/templates/sae_globals/contact.html
{% extends 'sae_globals/base.html' %}
{% load image_by_role %}
{% load crispy_forms_tags %}

{% block meta_title %}Contact{% endblock %}

{% block content %}
    {% include 'sae_globals/title_background.html' with title='Contact&nbsp;Us' image_role='CT' %}
    <div class="container contact-form-container">
        {% if request.GET.success %}
            <div class="alert alert-success my-4" role="alert">
                <strong>Success!</strong> Your message has been successfully received! We will get back to you as soon as possible.
            </div>
        {% elif form.errors %}
            <div class="alert alert-warning my-4" role="alert">
                <strong>Error!</strong> There was an issue submitting your message. Please correct any errors below.
            </div>
        {% endif %}
        <form role="form" action="" method="post"> {% csrf_token %}
            {{ form|crispy }}
            <div class="col-12 text-right">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

sae_globals/templates/sae_globals/contact_email.html
Contact Name: {{ contact_name }}

Email: {{ contact_email }}

Content:
{{ form_content|safe|striptags }}

sae_globals/templates/sae_globals/footer.html
<div id="footer">

</div>

sae_globals/templates/sae_globals/header.html
<nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'sae_globals:home' %}#">WPI SAE</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item"><a class="nav-link" href="{% url 'sae_globals:home' %}#">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'news:index' %}#">News</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'projects:index' %}#">Projects</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'images:index' %}#">Gallery</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'sponsors:index' %}#">Sponsors</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'sae_globals:contact' %}#">Contact</a></li>
        </ul>
    </div>
</nav>

sae_globals/templates/sae_globals/home.html
{% extends 'sae_globals/base.html' %}
{% load image_by_role %}

{% block content %}
    <div class="home-page-main">
        <img class="img-fluid mx-auto d-block" src="{% image_role 'HP' %}"/>
        <h3 class="text-center top-sps-title">Our Top Sponsors</h3>
        <div class="top-sps">
            {% for s in top_sponsors %}
                <a class="sp-logo" href="{{ s.url }}">
                    <img src="{{ s.logo_url }}" class="img-fluid" alt="{{ s.name }}">
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

sae_globals/templates/sae_globals/post.html
<div class="card post {% if listitem %}post-list-item{% endif %}">
    <a class="card-img-top" href="{{ post.image_file_url }}" data-toggle="lightbox" data-type="image">
        <img class="img-fluid" src="{{ post.image_file_url }}" alt="{{ post.image.title }}">
    </a>
    <div class="card-block">

        <h4 class="card-title">
            {% if listitem %}
                <a href="{{ post.abs_url }}">{{ post.title|safe }}</a>
            {% else %}
                {{ post.title|safe }}
            {% endif %}
        </h4>

        {% if show_created_by %}
            <h6 class="card-subtitle text-muted">By {{ post.created_by }}</h6>
        {% endif %}

        {% if listitem %}
            {% with post.content|safe|linebreaksbr|truncatewords_html:80 as content %}
                <p class="card-text">{{ content }}</p>
            {% endwith %}
            <p class="card-text text-right"><a href="{{ post.abs_url }}">Continue reading...</a></p>
        {% else %}
            {% with post.content|safe|linebreaksbr as content %}
                <p class="card-text">{{ content }}</p>
            {% endwith %}
        {% endif %}

        {% if show_pub_date %}
            <p class="card-text text-right">
                <small class="text-muted">Published {{ post.pub_date|date }}</small>
            </p>
        {% endif %}

    </div>
</div>

sae_globals/templates/sae_globals/title_background.html
{% load image_by_role %}
<div class="title-background">
    <div class="floating-title">
        <h3>{{ title }}</h3>
        {% if subtitle %}
            <h4>{{ subtitle }}</h4>
        {% endif %}
    </div>
    <img src="{% image_role image_role %}" class="img-fluid" title="{{ title }}" alt="title"/>
</div>